JDG-2214 Custom User Configuration
jboss-container-images/jboss-datagrid-7-openshift-image pull request #112
Opened 2018-10-23 09:45 UTC by ryanemerson

https://issues.jboss.org/browse/JDG-2214

@galderz Now issued against the datagrid73-dev branch. The example template has been moved to a documentation subdirectory and converted to yaml.

2018-10-23 15:54 UTC, galderz requested changes
Just one minor comment.

@ryanemerson Is @oraNod eventually putting this docu in the official docu? If so would we delete stuff from the repo? Or move it to a tutorial?

2018-10-23 15:54 UTC, galderz commented on docs/datagrid-user-xml.adoc
> +1. `oc create -f docs/examples/user-configuration/user-config-template.yaml`
Is `user-config-template.yaml` right? Seems like the file is called `user-xml-template.yaml` ?

2018-10-23 16:08 UTC, oraNod commented
@galderz @ryanemerson I've a task, JDG-2240, to cover the custom user config in the main OpenShift docs. I'd like to eventually remove the docs from this repo and point to the product docs.

2018-10-23 16:17 UTC, ryanemerson commented
@galderz Good spot about the name, I had missed that as part of the refactor. The .adoc and template files are both `*user-config.*`.

@galderz @oraNod Regarding the docs in general, shall we merge this as is and then delete the docs with JDG-2240? That way Don has these as a basis at least until the tutorials and prod documents are in place.

2018-10-23 16:18 UTC, ryanemerson commented
I also updated https://github.com/jboss-container-images/jboss-datagrid-7-openshift-image/pull/114

2018-10-24 11:02 UTC, galderz commented
Looks good now, integrating.

2018-10-24 11:02 UTC, galderz approved these changes

2018-10-24 11:03 UTC, merged