JDG-2256 Add REPLICATION_FACTOR template parameter to cache service
jboss-container-images/jboss-datagrid-7-openshift-image pull request #117
Opened 2018-11-02 07:14 UTC by galderz

https://issues.jboss.org/browse/JDG-2256

2018-11-02 12:55 UTC, galderz commented
The following appears in `ScalingTest` when trying to scale up:
```
[2018-11-02T07:30:34Z] [Warning] [Pod:cache-service-1]: 
(FailedScheduling) 0/1 nodes are available: 1 Insufficient cpu.
```

2018-11-05 12:05 UTC, galderz commented
@ryanemerson Updated PR. The custom cache service is now created/destroyed in the test, so the cost of the testsuite should remain the same (given that scaling test was already passing before). We do seem however to be close to the limit of the underlying VM for doing integration testing?

2018-11-05 13:12 UTC, ryanemerson requested changes

2018-11-05 13:12 UTC, ryanemerson commented on services/functional-tests/src/test/java/org/infinispan/online/service/utils/CommandLines.java
> +   private CommandLines() {
Unnecessary constructor

2018-11-05 13:12 UTC, ryanemerson commented on services/functional-tests/src/test/java/org/infinispan/online/service/utils/CommandLines.java
> +public class CommandLines {
I don't like having two classes with the names `CommandLines` and `CommandLine`. Could we not just add the static methods from `CommandLines` to `CommandLine`?

2018-11-05 13:12 UTC, ryanemerson commented on services/functional-tests/src/test/java/org/infinispan/online/service/caching/CustomCachingServiceTest.java
> +public class CustomCachingServiceTest {
It seems overkill to create a new test just for this. Is it possible to reuse `CachingServiceTest` with a Factory method that provides parameters for each test like we do in https://github.com/infinispan/infinispan? So in this case you would have two tests, one with num_owners=2 and the other with 3 with a generic method `should_have_replication_factor` and then check the configured "numOwners"?

The factory approach will also make it easy to test other startup parameter combinations as well as testing that changing any of those values does not break the caching service behaviour.

2018-11-06 12:56 UTC, ryanemerson commented on services/functional-tests/src/test/java/org/infinispan/online/service/utils/CommandLines.java
> +package org.infinispan.online.service.utils;
@galderz This still needs removing.

2018-11-06 13:47 UTC, galderz commented
@ryanemerson Should all be done now

2018-11-06 14:49 UTC, merged